spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/university_db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083