spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/university_db
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibername:
        format-sql: true

server:
  port: 8083